name: main

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup opam with setup-ocaml
        uses: ocaml/setup-ocaml@v2

      - name: Run the CI
        env:
          OCAML_VERSION: 4.12.0+domains+effects
        run: |
          bash -xe .ci.sh